language: Coq
sudo: required

before_install:
  - sudo add-apt-repository -y ppa:avsm/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq ocaml ocaml-native-compilers camlp4-extra opam

install:
  - opam init -a
  - eval `opam config env`
  - opam pin add -y coq 8.8.0

script:
  - ./configure.sh
  - make
